01/23/2023 10:48 PM - INFO - Configuration options are read from /home/ordabayev/repos/tapqir/.tapqir/config.yaml.
01/23/2023 10:48 PM - INFO - Fitting the data ...
01/23/2023 10:48 PM - ERROR - Failed to load data file
Traceback (most recent call last):
  File "/home/ordabayev/repos/tapqir/tapqir/utils/dataset.py", line 213, in load
    data_tapqir = torch.load(path / "data.tpqr")
  File "/home/ordabayev/anaconda3/envs/tapqir-dev/lib/python3.8/site-packages/torch/serialization.py", line 771, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/home/ordabayev/anaconda3/envs/tapqir-dev/lib/python3.8/site-packages/torch/serialization.py", line 270, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/home/ordabayev/anaconda3/envs/tapqir-dev/lib/python3.8/site-packages/torch/serialization.py", line 251, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: '/home/ordabayev/repos/tapqir/data.tpqr'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ordabayev/repos/tapqir/tapqir/main.py", line 466, in fit
    model.load(cd)
  File "/home/ordabayev/repos/tapqir/tapqir/models/model.py", line 111, in load
    self.data = load(self.path, self.device)
  File "/home/ordabayev/repos/tapqir/tapqir/utils/dataset.py", line 215, in load
    raise TapqirFileNotFoundError("data", path / "data.tpqr")
tapqir.exceptions.TapqirFileNotFoundError: Unable to find data file '/home/ordabayev/repos/tapqir/data.tpqr'
